// example/rj_address_model.dart
//
// Simple nested model — annotate with @RjSafeParsable() so the generator
// picks it up and the parent model can reference it automatically.
//
// Run: dart run build_runner build --delete-conflicting-outputs
// This generates: rj_address_model.g.dart  (part file, do NOT edit)

import 'package:rj_safe_parser/rj_safe_parser.dart';

part 'rj_address_model.g.dart'; // ← generated by build_runner

@RjSafeParsable()
class RjAddressModel {
  final String city;
  final int zip;

  const RjAddressModel({required this.city, required this.zip});

  factory RjAddressModel.fromMap(Map<String, dynamic> map) =>
      _$RjAddressModelFromMap(map);

  Map<String, dynamic> toMap() => _$RjAddressModelToMap(this);

  @override
  String toString() => 'RjAddressModel(city: $city, zip: $zip)';
}
