// example/rj_product_model.dart
//
// Simpler example — primitives and a list, no nested model.
// Run: dart run build_runner build --delete-conflicting-outputs

import 'package:rj_safe_parser/rj_safe_parser.dart';

part 'rj_product_model.g.dart'; // ← generated by build_runner

@RjSafeParsable()
class RjProductModel {
  final int id;
  final String name;
  final double price;
  final bool inStock;
  final DateTime createdAt;
  final List<String> categories;

  const RjProductModel({
    required this.id,
    required this.name,
    required this.price,
    required this.inStock,
    required this.createdAt,
    required this.categories,
  });

  factory RjProductModel.fromMap(Map<String, dynamic> map) =>
      _$RjProductModelFromMap(map);

  Map<String, dynamic> toMap() => _$RjProductModelToMap(this);

  @override
  String toString() =>
      'RjProductModel(id: $id, name: $name, price: $price)';
}
