// example/rj_user_model.dart
//
// Full example with every supported field type.
// Run: dart run build_runner build --delete-conflicting-outputs

import 'package:rj_safe_parser/rj_safe_parser.dart';
import 'rj_address_model.dart';

part 'rj_user_model.g.dart'; // ← generated by build_runner

@RjSafeParsable()
class RjUserModel {
  final int id;
  final String name;
  final String? nickname;             // nullable = optional
  final double score;
  final bool isActive;
  final DateTime createdAt;
  final Uri profileUrl;
  final RjAddressModel address;       // nested @RjSafeParsable
  final List<String> tags;            // list of primitives
  final List<RjAddressModel> history; // list of nested models

  const RjUserModel({
    required this.id,
    required this.name,
    this.nickname,
    required this.score,
    required this.isActive,
    required this.createdAt,
    required this.profileUrl,
    required this.address,
    required this.tags,
    required this.history,
  });

  factory RjUserModel.fromMap(Map<String, dynamic> map) =>
      _$RjUserModelFromMap(map);

  Map<String, dynamic> toMap() => _$RjUserModelToMap(this);

  @override
  String toString() =>
      'RjUserModel(id: $id, name: $name, createdAt: $createdAt)';
}

void main() {
  final dirtyJson = <String, dynamic>{
    'id': '7',           // string → coerced to int
    'name': 'Alice',
    'score': '9.8',      // string → coerced to double
    'isActive': 1,       // int    → coerced to bool
    'createdAt': 1712620800, // unix ts → coerced to DateTime
    'profileUrl': 'https://example.com/alice',
    'address': {'city': 'Dhaka', 'zip': '1212'}, // zip string → int
    'tags': ['dart', 'flutter'],
    'history': [
      {'city': 'Chittagong', 'zip': 4000},
    ],
  };

  final user = RjUserModel.fromMap(dirtyJson);
  print('id        : ${user.id}         (${user.id.runtimeType})');
  print('name      : ${user.name}');
  print('nickname  : ${user.nickname}   (absent → null)');
  print('score     : ${user.score}      (${user.score.runtimeType})');
  print('isActive  : ${user.isActive}   (${user.isActive.runtimeType})');
  print('createdAt : ${user.createdAt}');
  print('profileUrl: ${user.profileUrl}');
  print('address   : ${user.address}');
  print('tags      : ${user.tags}');
  print('history   : ${user.history}');
  print('\ntoMap(): ${user.toMap()}');
}
